services:
  postgres:
    container_name: postgres-search-engine
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${DB_NAME:-search_engine}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - search-engine-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME:-admin} -d ${DB_NAME:-search_engine}",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    container_name: kafka-search-engine
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "${KAFKA_PORT:-9092}:9092"
      - "9093:9093"
    environment:
      # KRaft mode configuration (no Zookeeper)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      # Cluster configuration
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      # Replication and Durability
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1

      # Performance Tuning
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_COMPRESSION_TYPE: snappy
      KAFKA_LOG_CLEANUP_POLICY: delete
      KAFKA_LOG_RETENTION_HOURS: 168 # 7 days
      KAFKA_LOG_SEGMENT_BYTES: 1073741824 # 1GB

      # Auto Topic Creation
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"

      # Message Size Configuration
      KAFKA_MESSAGE_MAX_BYTES: 10485760 # 10MB
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_PRODUCER_MAX_REQUEST_SIZE: 10485760
      KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES: 10485760

      # JVM Performance
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      KAFKA_JVM_PERFORMANCE_OPTS: "-server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35"

    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - search-engine-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics",
          "--bootstrap-server",
          "localhost:9092",
          "--list",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    container_name: redis-search-engine
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - search-engine-network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  search-engine-network:
    driver: bridge
    name: search-engine-network

volumes:
  postgres:
    driver: local
  redis_data:
    driver: local
  kafka_data:
    driver: local
