server:
  port: ${AUTH_SERVER_PORT:8080}

spring:
  application:
    name: auth-server
  config:
    import: optional:configserver:http://localhost:${CONFIG_SERVER_PORT:8888}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true