server:
  port: ${GATEWAY_PORT:8081}

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:${CONFIG_SERVER_PORT:8888}
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth-server/**
          filters:
            - StripPrefix=2
        - id: crawler-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/crawler-service/**
          filters:
            - StripPrefix=2
            - RewritePath=/(?<segment>.*), /crawler/$\{segment}
        - id: indexer-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/indexer-service/**
          filters:
            - StripPrefix=2
            - RewritePath=/(?<segment>.*), /indexer/$\{segment}
        - id: query-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/query-service/**
          filters:
            - StripPrefix=2
            - RewritePath=/(?<segment>.*), /query/$\{segment}

jwt:
  secret: ${JWT_SECRET:mySecretKey12345678901234567890123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
