server:
  port: 8081

spring:
  application:
    name: gateway
  
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth-server/**
          filters:
            - StripPrefix=1
            
        - id: query-service
          uri: lb://query
          predicates:
            - Path=/query-service/**
          filters:
            - StripPrefix=1
            
        - id: crawler-service
          uri: lb://crawler
          predicates:
            - Path=/crawler-service/**
          filters:
            - StripPrefix=1
            
        - id: indexer-service
          uri: lb://indexer
          predicates:
            - Path=/indexer-service/**
          filters:
            - StripPrefix=1
    
    config:
      enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG