server:
  port: ${QUERY_PORT:8084}

spring:
  application:
    name: query
  config:
    import: optional:configserver:http://localhost:${CONFIG_SERVER_PORT:8888}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

# Internal service authentication
service:
  internal:
    token: ${INTERNAL_SERVICE_TOKEN:search-engine-internal-token-2024}
